###################################################################
# If you want o support this repository I accept donations        #
# even 1 TOK is always welcome :-)!                               #
# > ethereum address: 0x44F102616C8e19fF3FED10c0b05B3d23595211ce  #
# > tokugawa address: TjrQBaaCPoVW9mPAZHPfVx9JJCq7yZ7QnA          #
###################################################################
#SECTION FOR BOT STYLE PARAMETERS
STYLE:
  FRAME:
    default_color:  0x00ff00
    error_color:    0xff0000

#SECTION FOR COIN SPECIFIC PARAMETERS
COIN:
    name:           Loki
    acronym:        LOKI
    decimals:       10
    explorer_url:   file:///tmp/loki_balance.txt
    collateral:     45000

#SECTION FOR MASTERNODES
MASTERNODES:
    - name:           SN01
      setup_date:     20/09/2018
      setup_balance:  45005                         #Indicate start balance was higher than collateral
      address:        YOUR_MASTERNODE_ADDRESS_1
      INVESTORS:
        - name:       INVESTOR_NAME_1
          coins:      15000
        - name:       INVESTOR_NAME_1
          coins:      15000
        - name:       INVESTOR_NAME_1
          coins:      15000
      EXPENSES:
        - description: EXPENSE_DESCRIPTION_1
          coins:       EXPENSE_COST1_LOK
        operator:      OPERATOR_FEE_PERCENTAGE      # 0.01.. (1 percent) etc

#SECTION FOR DISCORD PARAMETERS
DISCORD:
    api_key:          YOUR_DISCORD_API_KEY
