###################################################################
# If you want o support this repository I accept donations        #
# even 1 TOK is always welcome :-)!                               #
# > ethereum address: 0x44F102616C8e19fF3FED10c0b05B3d23595211ce  #
# > tokugawa address: TaJHPdZVGutRS9PzbYW9NojjpboeFM1w4A          #
###################################################################
#SECTION FOR BOT STYLE PARAMETERS
STYLE:
  FRAME:
    default_color:  0xff0000
    error_color:    0xcc0000

#SECTION FOR COIN SPECIFIC PARAMETERS
COIN:
    name:           Tokugawa
    acronym:        TOK
    decimals:       6
    explorer_url:   http://explorer.tokugawacoin.com/ext/getaddress/
    collateral:     2500

#SECTION FOR MASTERNODES
MASTERNODES:
    - name:           MN01
      setup_date:     13/09/2018
      setup_balance:  2500
      address:        YOUR_MASTERNODE_ADDRESS_1
      operator_fee:   OPERATOR_FEE_PERCENTAGE       #0.01.. (1 percent) etc

      #Non mandarory if you have a share masternode and want to show investors information
      INVESTORS:
        - name:       INVESTOR_NAME_1
          coins:      1250
        - name:       INVESTOR_NAME_1
          coins:      1250

      #ALL RELATED MN EXPENSES ARE IN FIAT
      EXPENSES:
        - desc:       EXPENSE_DESCRIPTION_1
          cost:       EXPENSE_COST1

    - name:           MN02
      setup_date:     13/09/2018
      setup_balance:  2500
      address:        YOUR_MASTERNODE_ADDRESS_2
      operator_fee:   OPERATOR_FEE_PERCENTAGE       #0.01.. (1 percent) etc

      INVESTORS:
        - name:       INVESTOR_NAME_1
          coins:      1000
        - name:       INVESTOR_NAME_1
          coins:      1000
        - name:       INVESTOR_NAME_3
          coins:      500

      #ALL RELATED MN EXPENSES ARE IN FIAT
      EXPENSES:
        - desc:       EXPENSE_DESCRIPTION_1
          cost:       EXPENSE_COST1

    - name:           MN03
      setup_date:     13/09/2018
      setup_balance:  2500
      address:        YOUR_MASTERNODE_ADDRESS_3
      operator_fee:   OPERATOR_FEE_PERCENTAGE       #0.01.. (1 percent) etc

      INVESTORS:
        - name:       INVESTOR_NAME_1
          coins:      2500

      #ALL RELATED MN EXPENSES ARE IN FIAT
      EXPENSES:
        - desc:       EXPENSE_DESCRIPTION_1
          cost:       EXPENSE_COST1

#SECTION FOR OTHER ADDRESSES SHOWN IN BALANCE WHICH ARE NOT MASTERNODES
OTHER_ADDRESSES:
    - name:           PERS1
      address:        YOUR_PERSONAL_ADDRESS_1

    - name:           PERS2
      address:        YOUR_PERSONAL_ADDRESS_2

#SECTION FOR DISCORD PARAMETERS
DISCORD:
    api_key:          YOUR_DISCORD_API_KEY
